version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:12
    working_directory: ~/tmp/arkitektjs/helper


workflows:
  version: 2
  build and test:
    jobs:
      - build project
      - code styles:
          requires:
            - build project
      - unit tests:
          requires:
            - build project
      - deploy:
          requires:
            - code styles
            - unit tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  build project:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - arkitektjs-helper-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - arkitektjs-helper-
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/tmp/arkitektjs/helper
          paths: .
      - save_cache:
          key: arkitektjs-helper-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules
  unit tests:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/tmp/arkitektjs/helper
      - run:
          name: Show work directory
          command: pwd
      - run:
          name: Running tests
          command: npm run test
  code styles:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/tmp/arkitektjs/helper
      - run:
          name: Running code styles
          command: npm run eslint
  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/tmp/arkitektjs/helper
      - run:
          name: Authenticate With Registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > ~/tmp/arkitektjs/helper/.npmrc
      - run:
          name: Publish Package
          command: |
            PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
            npm pack
