version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:12
    working_directory: ~/tmp/deltarm/helper

workflows:
  version: 2
  build and test:
    jobs:
      - build project:
          context: DeltaRM
      - code styles:
          context: DeltaRM
          requires:
            - build project
      - unit tests:
          context: DeltaRM
          requires:
            - build project
      - deploy:
          context: DeltaRM
          requires:
            - code styles
            - unit tests
          filters:
            branches:
              only: master

jobs:
  build project:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - deltarm-helper-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - deltarm-helper-
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/tmp/deltarm/helper
          paths: .
      - save_cache:
          key: deltarm-helper-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules
  unit tests:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/tmp/deltarm/helper
      - run:
          name: Running tests
          command: npm run test:coveralls
      - store_artifacts:
          path: coverage

  code styles:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/tmp/deltarm/helper
      - run:
          name: Running code styles
          command: npm run style
  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/tmp/deltarm/helper
      - run:
          name: Authenticate With Registry & Publish Package
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > ~/tmp/deltarm/helper/.npmrc
            PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
            npm pack
            npm publish deltarm-helper-$PACKAGE_VERSION.tgz --access public
